name: Release
run-name: Release

on:
  workflow_dispatch:
    inputs:
      environment:
        type: string
        description: "Production environment"
        default: "pro"

jobs:
  build-windows:
    runs-on: windows-latest
    name: Build Windows Package
    outputs:
      version: ${{ steps.extract-version.outputs.version }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17 (Liberica Full)
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'liberica'
          java-package: jdk-full

      - name: Setup Maven
        uses: stCarolas/setup-maven@v4
        with:
          maven-version: 3.8.6

      - name: Extract version from pom.xml (Windows)
        id: extract-version
        shell: pwsh
        run: |
          [xml]$pom = Get-Content pom.xml
          $version = $pom.project.version
          echo "VERSION=$version" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8
          echo "version=$version" | Out-File -FilePath $env:GITHUB_OUTPUT -Encoding utf8 -Append

      - name: Build project with Maven
        run: mvn clean package

      - name: Run build.bat
        shell: cmd
        run: |
          cd script\jpackage
          build.bat %VERSION%

      - name: Archive Windows ZIP
        uses: actions/upload-artifact@v4
        with:
          name: LabelPlusFX-${{ env.VERSION }}-Win64
          path: ${{ github.workspace }}/script/jpackage/Output/LabelPlusFX-${{ env.VERSION }}-Win64.zip



  build-macos:
    runs-on: macos-latest
    name: Build macOS Package
    outputs:
      version: ${{ steps.extract-version.outputs.version }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17 (Liberica Full)
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'liberica'
          java-package: jdk-full

      - name: Extract version from pom.xml
        id: extract-version
        run: |
          VERSION=$(xpath -q -e '/project/version/text()' pom.xml)
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "version=$VERSION" >> $GITHUB_OUTPUT


      - name: Setup Maven
        uses: stCarolas/setup-maven@v4
        with:
          maven-version: 3.8.6

      - name: Build project with Maven
        run: mvn clean package

      - name: Run build.sh
        run: |
          cd script/jpackage
          ./build-macos.sh ${{ env.VERSION }}

      - name: Archive macOS ZIP
        uses: actions/upload-artifact@v4
        with:
          name: LabelPlusFX-${{ env.VERSION }}-Mac
          path: ${{ github.workspace }}/script/jpackage/Output/LabelPlusFX-${{ env.VERSION }}-Mac.zip



  build-linux:
    runs-on: ubuntu-latest
    name: Build Linux Package
    outputs:
      version: ${{ steps.extract-version.outputs.version }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17 (Liberica Full)
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'liberica'
          java-package: jdk-full

      - name: Extract version from pom.xml
        id: extract-version
        run: |
          VERSION=$(xpath -q -e '/project/version/text()' pom.xml)
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Setup Maven
        uses: stCarolas/setup-maven@v4
        with:
          maven-version: 3.8.6

      - name: Build project with Maven
        run: mvn clean package

      - name: Run build.sh
        run: |
          cd script/jpackage
          ./build-linux.sh ${{ env.VERSION }}

      - name: Archive Linux ZIP
        uses: actions/upload-artifact@v4
        with:
          name: LabelPlusFX-${{ env.VERSION }}-Linux
          path: ${{ github.workspace }}/script/jpackage/Output/LabelPlusFX-${{ env.VERSION }}-Linux.zip

  create-release:
    needs: [ build-windows, build-macos, build-linux ]
    runs-on: ubuntu-latest
    name: Create Draft GitHub Release
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: release/
          merge-multiple: true

      - name: List files after download
        run: ls -lh release/

      - name: Extract Current Version Changelog
        run: |
          VERSION="${{ needs.build-windows.outputs.version }}"
          echo "Extracting changelog for version: $VERSION"
          head -40 CHANGELOG.md
          sed -n "/^## \[$VERSION\]/,/^## \[/p" CHANGELOG.md | sed '1d;$d' > changelog.md
          cat changelog.md


      - name: Create Draft Release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ needs.build-windows.outputs.version }}
          name: ${{ needs.build-windows.outputs.version }}
          body_path: changelog.md
          draft: false
          prerelease: false
          files: |
            release/LabelPlusFX-${{ needs.build-windows.outputs.version }}-Win64.zip
            release/LabelPlusFX-${{ needs.build-macos.outputs.version }}-Mac.zip
            release/LabelPlusFX-${{ needs.build-linux.outputs.version }}-Linux.zip
