name: Release
run-name: Release

on:
  workflow_dispatch:
    inputs:
      environment:
        type: string
        description: "Production environment"
        default: "pro"

jobs:
  build-windows:
    runs-on: windows-latest
    name: Build Windows Package
    outputs:
      version: ${{ steps.extract-version.outputs.version }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17 (Liberica Full)
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'liberica'
          java-package: jdk-full

      - name: Setup Maven
        uses: stCarolas/setup-maven@v4
        with:
          maven-version: 3.8.6

      - name: Extract version from pom.xml (Windows)
        id: extract-version
        shell: pwsh
        run: |
          [xml]$pom = Get-Content pom.xml
          $version = $pom.project.version
          echo "VERSION=$version" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8
          echo "version=$version" | Out-File -FilePath $env:GITHUB_OUTPUT -Encoding utf8 -Append

      - name: Build project with Maven
        run: mvn clean package

      - name: Run build.bat
        shell: cmd
        run: |
          cd script\jpackage
          build.bat %VERSION%

      - name: Archive Windows ZIP
        uses: actions/upload-artifact@v4
        with:
          name: LabelPlusFX-${{ env.VERSION }}-Win64
          path: ${{ github.workspace }}/script/jpackage/Output/LabelPlusFX-${{ env.VERSION }}-Win64.zip

      - name: 真正伟大的tmate
        uses: mxschmitt/action-tmate@v3
