name: Test Release
run-name: Test Release


on:
  workflow_dispatch:
    inputs:
      environment:
        type: string
        description: "Deployment environment"
        default: "dev"

jobs:
  extract-version:
    runs-on: windows-latest
    name: Extract project version
    outputs:
      version: ${{ steps.get-version.outputs.version }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Extract version from pom.xml
        id: get-version
        shell: pwsh
        run: |
          [xml]$pom = Get-Content pom.xml
          $version = $pom.project.version
          echo "version=$version" | Out-File -FilePath $env:GITHUB_OUTPUT -Encoding utf8 -Append

  build-windows:
    runs-on: windows-latest
    name: Build Windows Package (Test)
    needs: [extract-version]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21 (Liberica Full)
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'liberica'
          java-package: jdk-full

      - name: Setup Maven
        uses: stCarolas/setup-maven@v4
        with:
          maven-version: 3.8.6

      - name: Set VERSION environment variable
        shell: pwsh
        run: |
          echo "VERSION=${{ needs.extract-version.outputs.version }}" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8

      - name: Build project with Maven
        run: mvn clean package

      - name: Run build.bat
        shell: cmd
        run: |
          cd script\jpackage
          build.bat %VERSION%

      - name: Archive Windows ZIP
        uses: actions/upload-artifact@v4
        with:
          name: LabelPlusFX-${{ env.VERSION }}-Win64
          path: ${{ github.workspace }}/script/jpackage/Output/LabelPlusFX-${{ env.VERSION }}-Win64.zip


  build-macos:
    runs-on: macos-latest
    name: Build macOS Package (Test)
    needs: [extract-version]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21 (Liberica Full)
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'liberica'
          java-package: jdk-full

      - name: Set VERSION environment variable
        run: |
          echo "VERSION=${{ needs.extract-version.outputs.version }}" >> $GITHUB_ENV

      - name: Setup Maven
        uses: stCarolas/setup-maven@v4
        with:
          maven-version: 3.8.6

      - name: Build project with Maven
        run: mvn clean package

      - name: Run build.sh
        run: |
          cd script/jpackage
          ./build-macos.sh ${{ env.VERSION }}

      - name: Archive macOS ZIP
        uses: actions/upload-artifact@v4
        with:
          name: LabelPlusFX-${{ env.VERSION }}-Mac
          path: ${{ github.workspace }}/script/jpackage/Output/LabelPlusFX-${{ env.VERSION }}-Mac.zip

  build-macos-intel:
    runs-on: macos-15-intel
    name: Build macOS Package (Intel Compatible)
    needs: [ extract-version ]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21 (Intel)
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'liberica'
          java-package: jdk-full
          architecture: x64

      - name: Set VERSION environment variable
        run: |
          echo "VERSION=${{ needs.extract-version.outputs.version }}" >> $GITHUB_ENV

#      - name: Setup Maven
#        uses: stCarolas/setup-maven@v4
#        with:
#          maven-version: 3.8.6

      - name: Build project with Maven
        run: mvn clean package

      - name: Run macOS Intel build script
        run: |
          cd script/jpackage
          chmod +x build-macos-intel.sh
          ./build-macos-intel.sh ${{ env.VERSION }}

      - name: Archive macOS Intel ZIP
        uses: actions/upload-artifact@v4
        with:
          name: LabelPlusFX-${{ env.VERSION }}-Mac-Intel
          path: ${{ github.workspace }}/script/jpackage/Output/LabelPlusFX-${{ env.VERSION }}-Mac-Intel.zip

  build-linux:
    runs-on: ubuntu-latest
    name: Build Linux Package (Test)
    needs: [extract-version]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21 (Liberica Full)
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'liberica'
          java-package: jdk-full

      - name: Set VERSION environment variable
        run: |
          echo "VERSION=${{ needs.extract-version.outputs.version }}" >> $GITHUB_ENV

#      - name: Setup Maven
#        uses: stCarolas/setup-maven@v4
#        with:
#          maven-version: 3.8.6

      - name: Build project with Maven
        run: mvn clean package

      - name: Run build.sh
        run: |
          cd script/jpackage
          ./build-linux.sh ${{ env.VERSION }}

      - name: Archive Linux ZIP
        uses: actions/upload-artifact@v4
        with:
          name: LabelPlusFX-${{ env.VERSION }}-Linux
          path: ${{ github.workspace }}/script/jpackage/Output/LabelPlusFX-${{ env.VERSION }}-Linux.tar.gz

  create-release:
    needs: [ extract-version, build-windows, build-macos, build-macos-intel, build-linux ]
    runs-on: ubuntu-latest
    name: Create Draft GitHub Release
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: release/
          merge-multiple: true

      - name: List files after download
        run: ls -lh release/

      - name: Extract Current Version Changelog
        run: |
          VERSION="${{ needs.extract-version.outputs.version }}"
          echo "Extracting changelog for version: $VERSION"
          head -40 CHANGELOG.md
          sed -n "/^## \[$VERSION\]/,/^## \[/p" CHANGELOG.md | sed '1d;$d' > changelog.md
          cat changelog.md

      - name: Create Draft Release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ needs.extract-version.outputs.version }}-test
          name: ${{ needs.extract-version.outputs.version }}-test
          body_path: changelog.md
          draft: true
          prerelease: false
          files: |
            release/LabelPlusFX-${{ needs.extract-version.outputs.version }}-Win64.zip
            release/LabelPlusFX-${{ needs.extract-version.outputs.version }}-Mac.zip
            release/LabelPlusFX-${{ needs.extract-version.outputs.version }}-Mac-Intel.zip
            release/LabelPlusFX-${{ needs.extract-version.outputs.version }}-Linux.tar.gz
          
